export enum NogiMember {
  nogizaka46 = "乃木坂46",

  Akimoto_Manatsu = "秋元真夏",
  Ikuta_Erika = "生田絵梨花",
  Nakada_Kana = "中田花奈",
  Matsumura_Sayuri = "松村沙友理",
  Saito_Chiharu = "斎藤ちはる",
  Saito_Asuka = "齋藤飛鳥",
  Takayama_Kazumi = "高山一実",
  Higuchi_Hina = "樋口日奈",
  Wada_Maaya = "和田まあや",
  Kashiwa_Yukina = "柏幸奈",
  Miyazawa_Seira = "宮澤成良",
  Ichiki_Rena = "市來玲奈",
  Ito_Nene = "伊藤寧々",
  Hatanaka_Seira = "畠中清羅",
  Nagashima_Seira = "永島聖羅",
  Fukagawa_Mai = "深川麻衣",
  Nakamoto_Himeka = "中元日芽香",
  Ito_Marika = "伊藤万理華",
  Kawamura_Mahiro = "川村真洋",
  Ikoma_Rina = "生駒里奈",
  Wakatsuki_Yumi = "若月佑美",
  Nojo_Ami = "能條愛未",
  Kawago_Hina = "川後陽菜",
  Nishino_Nanase = "西野七瀬",
  Eto_Misa = "衛藤美彩",
  Saito_Yuuri = "斉藤優里",
  Sakurai_Reika = "桜井玲香",
  Inoue_Sayuri = "井上小百合",
  Shiraishi_Mai = "白石麻衣",

  Ito_Karin = "伊藤かりん",
  Ito_Junna = "伊藤純奈",
  Kitano_Hinako = "北野日奈子",
  Shinuchi_Mai = "新内眞衣",
  Watanabe_Miria = "渡辺みり愛",
  Yamazaki_Rena = "山崎怜奈",
  Suzuki_Ayane = "鈴木絢音",
  Sagara_Iori = "相楽伊織",
  Sasaki_Kotoko = "佐々木琴子",
  Hori_Miona = "堀未央奈",
  Terada_Ranze = "寺田蘭世",


  Ito_Riria = "伊藤理々杏",
  Iwamoto_Renka = "岩本蓮加",
  Umezawa_Minami = "梅澤美波",
  Kubo_Shiori = "久保史緒里",
  Sakaguchi_Tamami = "阪口珠美",
  Sato_Kaede = "佐藤楓",
  Nakamura_Reno = "中村麗乃",
  Mukai_Hazuki = "向井葉月",
  Yamashita_Mizuki = "山下美月",
  Yoshida_AyanoChristie = "吉田綾乃クリスティー",
  Yoda_Yuuki = "与田祐希",
  Ozono_Momoko = "大園桃子",

  Endo_Sakura = "遠藤さくら",
  Kaki_Haruka = "賀喜遥香",
  Kakehashi_Sayaka = "掛橋沙耶香",
  Kanagawa_Saya = "金川紗耶",
  Kitagawa_Yuri = "北川悠理",
  Kuromi_Haruka = "黒見明香",
  Sato_Rika = "佐藤璃果",
  Shibata_Yuna = "柴田柚菜",
  Seimiya_Rei = "清宮レイ",
  Tamura_Mayu = "田村真佑",
  Tsutsui_Ayame = "筒井あやめ",
  Hayakawa_Seira = "早川聖来",
  Hayashi_Runa = "林瑠奈",
  Matsuo_Miyu = "松尾美佑",
  Yakubo_Mio = "矢久保美緒",
  Yumiki_Nao = "弓木奈於",

  Ioki_Mao = "五百城茉央",
  Ikeda_Teresa = "池田瑛紗",
  Ichinose_Miku = "一ノ瀬美空",
  Inoue_Nagi = "井上和",
  Okamoto_Hina = "岡本姫奈",
  Ogawa_Aya = "小川彩",
  Okuda_Iroha = "奥田いろは",
  Kawasaki_Sakura = "川﨑桜",
  Sugawara_Satsuki = "菅原咲月",
  Tomisato_Nao = "冨里奈央",
  Nakanishi_Aruno = "中西アルノ",
}

export const NogiCurrentMembers = [
  NogiMember.nogizaka46,

  NogiMember.Ito_Riria,
  NogiMember.Iwamoto_Renka,
  NogiMember.Umezawa_Minami,
  NogiMember.Kubo_Shiori,
  NogiMember.Sakaguchi_Tamami,
  NogiMember.Sato_Kaede,
  NogiMember.Nakamura_Reno,
  NogiMember.Mukai_Hazuki,
  NogiMember.Yamashita_Mizuki,
  NogiMember.Yoshida_AyanoChristie,
  NogiMember.Yoda_Yuuki,

  NogiMember.Endo_Sakura,
  NogiMember.Kaki_Haruka,
  NogiMember.Kakehashi_Sayaka,
  NogiMember.Kanagawa_Saya,
  NogiMember.Kitagawa_Yuri,
  NogiMember.Kuromi_Haruka,
  NogiMember.Sato_Rika,
  NogiMember.Shibata_Yuna,
  NogiMember.Seimiya_Rei,
  NogiMember.Tamura_Mayu,
  NogiMember.Tsutsui_Ayame,
  NogiMember.Hayakawa_Seira,
  NogiMember.Hayashi_Runa,
  NogiMember.Matsuo_Miyu,
  NogiMember.Yakubo_Mio,
  NogiMember.Yumiki_Nao,

  NogiMember.Ioki_Mao,
  NogiMember.Ikeda_Teresa,
  NogiMember.Ichinose_Miku,
  NogiMember.Inoue_Nagi,
  NogiMember.Okamoto_Hina,
  NogiMember.Ogawa_Aya,
  NogiMember.Okuda_Iroha,
  NogiMember.Kawasaki_Sakura,
  NogiMember.Sugawara_Satsuki,
  NogiMember.Tomisato_Nao,
  NogiMember.Nakanishi_Aruno,
];

export const NogiGraduateMembers = [
  NogiMember.Akimoto_Manatsu,
  NogiMember.Ikuta_Erika,
  NogiMember.Nakada_Kana,
  NogiMember.Matsumura_Sayuri,
  NogiMember.Saito_Asuka,
  NogiMember.Saito_Chiharu,
  NogiMember.Takayama_Kazumi,
  NogiMember.Higuchi_Hina,
  NogiMember.Wada_Maaya,
  NogiMember.Kashiwa_Yukina,
  NogiMember.Miyazawa_Seira,
  NogiMember.Ichiki_Rena,
  NogiMember.Ito_Nene,
  NogiMember.Hatanaka_Seira,
  NogiMember.Nagashima_Seira,
  NogiMember.Fukagawa_Mai,
  NogiMember.Nakamoto_Himeka,
  NogiMember.Ito_Marika,
  NogiMember.Kawamura_Mahiro,
  NogiMember.Ikoma_Rina,
  NogiMember.Wakatsuki_Yumi,
  NogiMember.Nojo_Ami,
  NogiMember.Kawago_Hina,
  NogiMember.Nishino_Nanase,
  NogiMember.Eto_Misa,
  NogiMember.Saito_Yuuri,
  NogiMember.Sakurai_Reika,
  NogiMember.Inoue_Sayuri,
  NogiMember.Shiraishi_Mai,

  NogiMember.Ito_Karin,
  NogiMember.Ito_Junna,
  NogiMember.Kitano_Hinako,
  NogiMember.Shinuchi_Mai,
  NogiMember.Suzuki_Ayane,
  NogiMember.Watanabe_Miria,
  NogiMember.Yamazaki_Rena,
  NogiMember.Sagara_Iori,
  NogiMember.Sasaki_Kotoko,
  NogiMember.Hori_Miona,
  NogiMember.Terada_Ranze,

  NogiMember.Ozono_Momoko,
];